[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cldfbench_audersetinterrog"
dependencies = ["cldfbench[glottolog]"]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest-cldf"]

[project.entry-points."cldfbench.dataset"]
audersetinterrog = "cldfbench_audersetinterrog:Dataset"

[tool.setuptools]
py-modules = ["cldfbench_audersetinterrog"]
include-package-data = true

[tool.pytest.ini_options]
testpaths = ["test.py"]
addopts = "--cldf-metadata=cldf/StructureDataset-metadata.json"
